# Generated by Django 5.0.1 on 2024-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_description_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
